[package]
name = "drone"
version = "0.1.0"
edition = "2024"

[dependencies]
vulkano = "0.35.1"
vulkano-shaders = "0.35"
vulkano-util = "0.35"
winit = "0.30.12"
anyhow = "1.0"
cpal = "0.15.3"
rand = "0.9.2"
